### ISSUE TITLE
i am unable to install system-slepp

### ISSUE THREAD

**Issue by chananbental** [jochemstoel/nodejs-system-sleep#12]
the error i get:

> deasync@0.1.11 install C:\Yproject\project2\Roommates\node_modules\deasync
> node ./build.js

`win32-x64-node-9` exists; testing
Problem with the binary; manual build incoming
stdout=
err=Error: Command failed: C:\Program Files\nodejs\node.exe quick-test.js
C:\Yproject\project2\Roommates\node_modules\deasync\index.js:71
		process._tickDomainCallback();
		        ^

TypeError: process._tickDomainCallback is not a function
    at Function.module.exports.loopWhile (C:\Yproject\project2\Roommates\node_modules\deasync\index.js:71:11)
    at Function.sleep (C:\Yproject\project2\Roommates\node_modules\deasync\index.js:44:19)
    at Object.<anonymous> (C:\Yproject\project2\Roommates\node_modules\deasync\quick-test.js:6:34)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)

C:\Yproject\project2\Roommates\node_modules\deasync>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  deasync.cc
  win_delay_load_hook.cc
..\src\deasync.cc(1): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory [C:\Yproject\project2\Roommates\node_modules\deasync\build\deasync.vcxproj]

  gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Yproject\project2\Roommates\node_modules\deasync
gyp ERR! node -v v9.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Build failed

**Comment by jochemstoel** [comment]
You are receiving this error because deasync fails to build. Simply download this module here from GitHub and it will work fine.
